import './globals.css'
import { Inter, Montserrat_Alternates } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat_Alternates({ subsets: ['latin'], weight: ["400", "600"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
